---
version: '3'
services:
  node:
    image: mcr.microsoft.com/devcontainers/javascript-node:20
    volumes:
      - .:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
  
  db:
    image: mariadb:11
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: data
